version: '3.9'
services:
  langaudio_frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_URL: http://localhost:7000
        APP_URL: http://localhost:3000
    container_name: langaudio_frontend
    ports:
      - 3000:3000
    # env_file:
    #   - ./config/prod.env
    networks:
      - backend_langaudio_net
networks:
  backend_langaudio_net:
    external: true